### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'ParseError')

### ISSUE THREAD

**Issue by krzysztof99xd** [rbnvrw/katex-auto-render#1]
Hey, I am using your project on my website and recently I occured the following issue:
Uncaught TypeError: Cannot read properties of undefined (reading 'ParseError') at l (auto-render.min.js:1:2427) at e (auto-render.min.js:1:3177) at auto-render.min.js:1:3423 at e (auto-render.min.js:1:3430) at auto-render.min.js:1:3423 at e (auto-render.min.js:1:3430) at auto-render.min.js:1:3423 at e (auto-render.min.js:1:3430) at auto-render.min.js:1:3423 at e (auto-render.min.js:1:3430)

**Comment by rbnvrw** [comment]
Hi, I'm sorry, I can no longer maintain this project and I'll archive it, I hope you've found a solution in the meantime.
